CREATE SCHEMA IF NOT EXISTS raw_layer;
CREATE SCHEMA IF NOT EXISTS staging_layer;
CREATE SCHEMA IF NOT EXISTS presentation_layer;

CREATE TABLE IF NOT EXISTS raw_layer.raw_nyc_taxi_trip(
    VendorID INTEGER,
    tpep_pickup_datetime TIMESTAMP,
    tpep_dropoff_datetime TIMESTAMP,
    passenger_count BIGINT,
    trip_distance DOUBLE PRECISION,
    RatecodeID BIGINT, 
    store_and_fwd_flag VARCHAR, 
    PULocationID INTEGER,
    DOLocationID INTEGER,
    payment_type BIGINT, 
    fare_amount  DOUBLE PRECISION,
    extra DOUBLE PRECISION,
    mta_tax DOUBLE PRECISION,
    tip_amount DOUBLE PRECISION,
    tolls_amount DOUBLE PRECISION,
    improvement_surcharge DOUBLE PRECISION,
    total_amount DOUBLE PRECISION,
    congestion_Surcharge DOUBLE PRECISION,
    Airport_fee DOUBLE PRECISION
)DISTSTYLE EVEN;

CREATE TABLE IF NOT EXISTS staging_layer.staging_nyc_taxi_trip(
    pickup_datetime TIMESTAMP,
    dropoff_datetime TIMESTAMP,
    passenger_count SMALLINT,
    trip_distance DOUBLE PRECISION,
    pickup_location_id INTEGER,
    dropoff_location_id INTEGER,
    rate_code_id SMALLINT,
    payment_type SMALLINT,
    fare_amount DOUBLE PRECISION,
    total_amount DOUBLE PRECISION
)DISTSTYLE EVEN;   

CREATE TABLE IF NOT EXISTS presentation_layer.dim_date(
    date_key INT PRIMARY KEY NOT NULL,
    date DATE UNIQUE NOT NULL,
    day_of_month SMALLINT NOT NULL,
    day_of_week SMALLINT NOT NULL,
    date_of_week_name VARCHAR(10) NOT NULL,
    month SMALLINT NOT NULL,
    year SMALLINT NOT NULL,
    is_weekend BOOLEAN NOT NULL
)DISTSTYLE ALL
SORTKEY(date_key);

CREATE TABLE IF NOT EXISTS presentation_layer.dim_time(
    time_key SMALLINT PRIMARY KEY NOT NULL,
    hour SMALLINT NOT NULL,
    time_of_day VARCHAR(15) NOT NULL
)DISTSTYLE ALL
SORTKEY(time_key);

CREATE TABLE IF NOT EXISTS presentation_layer.dim_location(
    LocationID INT,
    borough VARCHAR,
    zone VARCHAR,
    service_zone VARCHAR
)DISTSTYLE ALL
SORTKEY(LocationID);

CREATE TABLE IF NOT EXISTS presentation_layer.dim_rate_code(
    rate_code_id SMALLINT PRIMARY KEY NOT NULL,
    rate_code_name VARCHAR(25) NOT NULL
)DISTSTYLE ALL;

CREATE TABLE IF NOT EXISTS presentation_layer.dim_payment_type(
    payment_type SMALLINT PRIMARY KEY NOT NULL,
    payment_type_name VARCHAR(20) NOT NULL
)DISTSTYLE ALL;

CREATE TABLE IF NOT EXISTS presentation_layer.fact_trip(
    trip_id INT PRIMARY KEY NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    pickup_date_key INT NOT NULL,
    dropoff_date_key INT NOT NULL,
    pickup_time_key SMALLINT NOT NULL,
    dropoff_time_key SMALLINT NOT NULL,
    rate_code_id SMALLINT NOT NULL,
    payment_type SMALLINT NOT NULL,
    passenger_count SMALLINT NOT NULL,
    pickup_location_key INT NOT NULL,
    dropoff_location_key INT NOT NULL,
    trip_duration INT NOT NULL,
    trip_distance DOUBLE PRECISION NOT NULL,
    fare_amount DOUBLE PRECISION NOT NULL,
    total_amount DOUBLE PRECISION NOT NULL
)DISTSTYLE EVEN
SORTKEY(pickup_date_key, pickup_time_key, pickup_location_key);
